---
 driver:
   name: docker

 platforms: #a list of OS on which we're going to run the tests
   - name: ubuntu
     driver:
       image: <%= $DOCKER_HUB_IMAGE %>
# driver: 
#   username: <%= $DOCKER_HUB_USERNAME %>
#   password: <%= $DOCKER_HUB_PASSWORD %>
#   dockerfile: firedot/xenial_nginx

 suites: 
 - name: default
   driver: 
     provision_command: true
   verifier: 
     name: inspec
